"""Init DB

Revision ID: ade8ad9abe84
Revises: 
Create Date: 2026-05-01 00:39:17.185596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade8ad9abe84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('real_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('secondary_consent_given', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_map_hash_id'), 'identity_map', ['hash_id'], unique=True)
    op.create_index(op.f('ix_identity_map_id'), 'identity_map', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'coordinator', 'pharma', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharma_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('disease', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location_preference', sa.String(length=255), nullable=True),
    sa.Column('exclusion_criteria', sa.Text(), nullable=True),
    sa.Column('inclusion_criteria', sa.Text(), nullable=True),
    sa.Column('patients_needed', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'draft', name='trialstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharma_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trials_id'), 'trials', ['id'], unique=False)
    op.create_table('extracted_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('user_handle', sa.String(length=255), nullable=True),
    sa.Column('extracted_conditions', sa.JSON(), nullable=True),
    sa.Column('extracted_symptoms', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_candidates_id'), 'extracted_candidates', ['id'], unique=False)
    op.create_table('raw_medical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_medical_data_id'), 'raw_medical_data', ['id'], unique=False)
    op.create_table('social_raw_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('user_handle', sa.String(length=255), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_raw_posts_id'), 'social_raw_posts', ['id'], unique=False)
    op.create_table('verified_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('fhir_bundle_json', sa.JSON(), nullable=True),
    sa.Column('report_s3_url', sa.String(length=500), nullable=True),
    sa.Column('wearable_data_s3_url', sa.String(length=500), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending_consent', 'consent_given', 'opted_out', 'no_response', 'enrolled', 'fraud_flagged', 'withdrawn', name='candidatestatus'), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_patients_hash_id'), 'verified_patients', ['hash_id'], unique=True)
    op.create_index(op.f('ix_verified_patients_id'), 'verified_patients', ['id'], unique=False)
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('biometric_type', sa.String(length=100), nullable=True),
    sa.Column('patient_value', sa.Float(), nullable=True),
    sa.Column('cohort_mean', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('alert_tier', sa.Enum('RED', 'AMBER', 'GREEN', name='alerttier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['verified_patients.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_id'), 'anomaly_alerts', ['id'], unique=False)
    op.create_table('consent_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('message_sent', sa.Text(), nullable=True),
    sa.Column('response', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['extracted_candidates.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_audit_log_id'), 'consent_audit_log', ['id'], unique=False)
    op.create_table('dropout_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.Enum('RED', 'AMBER', 'GREEN', name='alerttier'), nullable=False),
    sa.Column('days_since_login', sa.Integer(), nullable=True),
    sa.Column('symptom_logs_week', sa.Integer(), nullable=True),
    sa.Column('wearable_uploads_week', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['verified_patients.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dropout_scores_id'), 'dropout_scores', ['id'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['extracted_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_id'), 'fraud_flags', ['id'], unique=False)
    op.create_table('matched_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_tier', sa.Enum('HIGH', 'MEDIUM', name='matchtier'), nullable=False),
    sa.Column('status', sa.Enum('pending_consent', 'consent_given', 'opted_out', 'no_response', 'enrolled', 'fraud_flagged', 'withdrawn', name='candidatestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['extracted_candidates.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matched_candidates_id'), 'matched_candidates', ['id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('symptoms_json', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['verified_patients.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_id'), 'symptom_logs', ['id'], unique=False)
    op.create_table('wearable_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Float(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['verified_patients.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wearable_data_id'), 'wearable_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wearable_data_id'), table_name='wearable_data')
    op.drop_table('wearable_data')
    op.drop_index(op.f('ix_symptom_logs_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_matched_candidates_id'), table_name='matched_candidates')
    op.drop_table('matched_candidates')
    op.drop_index(op.f('ix_fraud_flags_id'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_dropout_scores_id'), table_name='dropout_scores')
    op.drop_table('dropout_scores')
    op.drop_index(op.f('ix_consent_audit_log_id'), table_name='consent_audit_log')
    op.drop_table('consent_audit_log')
    op.drop_index(op.f('ix_anomaly_alerts_id'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    op.drop_index(op.f('ix_verified_patients_id'), table_name='verified_patients')
    op.drop_index(op.f('ix_verified_patients_hash_id'), table_name='verified_patients')
    op.drop_table('verified_patients')
    op.drop_index(op.f('ix_social_raw_posts_id'), table_name='social_raw_posts')
    op.drop_table('social_raw_posts')
    op.drop_index(op.f('ix_raw_medical_data_id'), table_name='raw_medical_data')
    op.drop_table('raw_medical_data')
    op.drop_index(op.f('ix_extracted_candidates_id'), table_name='extracted_candidates')
    op.drop_table('extracted_candidates')
    op.drop_index(op.f('ix_trials_id'), table_name='trials')
    op.drop_table('trials')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_identity_map_id'), table_name='identity_map')
    op.drop_index(op.f('ix_identity_map_hash_id'), table_name='identity_map')
    op.drop_table('identity_map')
    # ### end Alembic commands ###
